[project]
name = "viam-isaac-sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.11.0"
dependencies = [
    # todo: experiment with smaller extras here
    "isaacsim[all,extscache]==5.0.0",
    "viam-sdk>=0.84.0",
]

[tool.uv]
override-dependencies = [
    # resolves a conflict between isaacsim and viam-sdk
    "typing-extensions>=4.15.0"
]

[[tool.uv.index]]
url = "https://pypi.nvidia.com/"
